stages:
  - init
  - backendtest
  - frontendonetest
  - frontendonelint
  - frontendtwolint
  - serverpylint

environment:
  stage: init
  script:
    - python3 -m venv ~/venv
    - source ~/venv/bin/activate
    - pip install --upgrade pip
    - pip install Django mysqlclient
    - pip install Pillow

backendtest:
  stage: backendtest
  script:
    - source ~/venv/bin/activate
    - python ./server/manage.py makemigrations backend
    - python ./server/manage.py migrate
    - cd ./server
    - pip3 install coverage --quiet
    - python -m coverage run --source="." manage.py test
    - python -m coverage report

frontendonetest:
  stage: frontendonetest
  script:
    - cd ./frontend
    - npm install
    - npm test

frontendonelint:
  stage: frontendonelint
  script:
    - cd ./frontend
    - npm install --save-dev eslint eslint-plugin-vue@next
    - npm run eslint

frontendtwolint:
  stage: frontendtwolint
  script:
    - cd ./frontend2
    - npm install --save-dev eslint eslint-plugin-vue@next
    - npm run eslint

serverpylint:
  stage: serverpylint
  script:
    - cd ./server
    - pylint --rcfile=pylint.conf ./server/*
    - pylint --rcfile=pylint.conf ./backend/*

